apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "fullname" . | lower | snakecase }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    appName: {{ .Values.name | quote}}
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . | lower | snakecase }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | lower | snakecase }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{- include "image" . }}"
        imagePullPolicy: IfNotPresent
        env:
        {{- toYaml .Values.environments | nindent  10}}
