apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        resources:
          limits:
          # | quote é para adicionar aspas duplas no valor do comando
            memory: {{.Values.resourcelimits.memory | quote}}
            cpu: {{.Values.resourcelimits.cpu}}
        ports:
        - containerPort: {{.Values.port}}
