# Default values for cluster-bootstrap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  application:
    cluster:
      name: "in-cluster"
      server: "https://kubernetes.default.svc"
    project: default

sealedSecrets:
  enabled: true
  namespace: sealed-secrets

istioBase:
  enabled: true
  namespace: istio-system

istiod:
  enabled: true
  namespace: istio-system

istioGateway:
  enabled: true
  namespace: istio-ingress

certManager:
  enabled: true
  namespace: cert-manager

teste: ccc